// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'PurchaseModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$PurchaseModelImpl _$$PurchaseModelImplFromJson(Map<String, dynamic> json) =>
    _$PurchaseModelImpl(
      ID: (json['ID'] as num?)?.toInt(),
      UID: json['UID'] as String?,
      COCODE: json['COCODE'] as String?,
      DOCNUMBER: json['DOCNUMBER'] as String?,
      TXNDATE: json['TXNDATE'] as String?,
      PARTYBILLNO: json['PARTYBILLNO'] as String?,
      PARTYBILLDATE: json['PARTYBILLDATE'] as String?,
      DAYBOOK: json['DAYBOOK'] as String?,
      ACCOUNTCODE: json['ACCOUNTCODE'] as String?,
      ACCOUNTNAME: json['ACCOUNTNAME'] as String?,
      GROSSAMT: (json['GROSSAMT'] as num?)?.toDouble(),
      TAXABLEAMT: (json['TAXABLEAMT'] as num?)?.toDouble(),
      GST: (json['GST'] as num?)?.toDouble(),
      NETAMOUNT: (json['NETAMOUNT'] as num?)?.toDouble(),
      RECAMT: (json['RECAMT'] as num?)?.toDouble(),
      PendingStatus: json['PendingStatus'] as String?,
      DocumentID: (json['DocumentID'] as num?)?.toInt(),
      BROKERCODE: json['BROKERCODE'] as String?,
      BILLTERM: json['BILLTERM'] as String?,
      DeliveryCode: json['DeliveryCode'] as String?,
      StateOfSupply: json['StateOfSupply'] as String?,
      STATENAME: json['STATENAME'] as String?,
      GSTAmount: (json['GSTAmount'] as num?)?.toDouble(),
      DUEDAYS: (json['DUEDAYS'] as num?)?.toDouble(),
      ADD1: json['ADD1'] as String?,
      ADD2: json['ADD2'] as String?,
      PINCODE: json['PINCODE'] as String?,
      CITY: json['CITY'] as String?,
      GSTIN: json['GSTIN'] as String?,
      MOBILE: json['MOBILE'] as String?,
      DNAME: json['DNAME'] as String?,
      DADD1: json['DADD1'] as String?,
      DADD2: json['DADD2'] as String?,
      DPINCODE: json['DPINCODE'] as String?,
      DCITY: json['DCITY'] as String?,
      DGSTIN: json['DGSTIN'] as String?,
      DMOBILE: json['DMOBILE'] as String?,
      BROKERNAME: json['BROKERNAME'] as String?,
      LINEITEM: json['LINEITEM'] as String?,
      ITEMS: json['ITEMS'] as String?,
      Q1: json['Q1'] as String?,
      Q2: json['Q2'] as String?,
      Q3: json['Q3'] as String?,
      ORIGINALBILLNO: json['ORIGINALBILLNO'] as String?,
      ORIGINALBILLDT: json['ORIGINALBILLDT'] as String?,
      item: json['item'] == null
          ? null
          : LineItemModel.fromJson(json['item'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$PurchaseModelImplToJson(_$PurchaseModelImpl instance) =>
    <String, dynamic>{
      'ID': instance.ID,
      'UID': instance.UID,
      'COCODE': instance.COCODE,
      'DOCNUMBER': instance.DOCNUMBER,
      'TXNDATE': instance.TXNDATE,
      'PARTYBILLNO': instance.PARTYBILLNO,
      'PARTYBILLDATE': instance.PARTYBILLDATE,
      'DAYBOOK': instance.DAYBOOK,
      'ACCOUNTCODE': instance.ACCOUNTCODE,
      'ACCOUNTNAME': instance.ACCOUNTNAME,
      'GROSSAMT': instance.GROSSAMT,
      'TAXABLEAMT': instance.TAXABLEAMT,
      'GST': instance.GST,
      'NETAMOUNT': instance.NETAMOUNT,
      'RECAMT': instance.RECAMT,
      'PendingStatus': instance.PendingStatus,
      'DocumentID': instance.DocumentID,
      'BROKERCODE': instance.BROKERCODE,
      'BILLTERM': instance.BILLTERM,
      'DeliveryCode': instance.DeliveryCode,
      'StateOfSupply': instance.StateOfSupply,
      'STATENAME': instance.STATENAME,
      'GSTAmount': instance.GSTAmount,
      'DUEDAYS': instance.DUEDAYS,
      'ADD1': instance.ADD1,
      'ADD2': instance.ADD2,
      'PINCODE': instance.PINCODE,
      'CITY': instance.CITY,
      'GSTIN': instance.GSTIN,
      'MOBILE': instance.MOBILE,
      'DNAME': instance.DNAME,
      'DADD1': instance.DADD1,
      'DADD2': instance.DADD2,
      'DPINCODE': instance.DPINCODE,
      'DCITY': instance.DCITY,
      'DGSTIN': instance.DGSTIN,
      'DMOBILE': instance.DMOBILE,
      'BROKERNAME': instance.BROKERNAME,
      'LINEITEM': instance.LINEITEM,
      'ITEMS': instance.ITEMS,
      'Q1': instance.Q1,
      'Q2': instance.Q2,
      'Q3': instance.Q3,
      'ORIGINALBILLNO': instance.ORIGINALBILLNO,
      'ORIGINALBILLDT': instance.ORIGINALBILLDT,
      'item': instance.item,
    };
