// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'OrderModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$OrderModelImpl _$$OrderModelImplFromJson(Map<String, dynamic> json) =>
    _$OrderModelImpl(
      ReferenceNo: json['ReferenceNo'] as String?,
      TrTransportName: json['TrTransportName'] as String?,
      TrLRNo: json['TrLRNo'] as String?,
      TrLRDate: json['TrLRDate'] as String?,
      TrNoOfParcel: json['TrNoOfParcel'] as String?,
      TrSourceCity: json['TrSourceCity'] as String?,
      TrStation: json['TrStation'] as String?,
      DeliveryCode: json['DeliveryCode'] as String?,
      DeliveryName: json['DeliveryName'] as String?,
      AccountAddress: json['AccountAddress'] as String?,
      SPEQOHID: (json['SPEQOHID'] as num?)?.toInt(),
      SPEQOLiID: (json['SPEQOLiID'] as num?)?.toInt(),
      dbktype: json['dbktype'] as String?,
      OrderDate: json['OrderDate'] as String?,
      SPEQOhSPEQOLi: (json['SPEQOhSPEQOLi'] as num?)?.toInt(),
      MonthName: json['MonthName'] as String?,
      MonthGroup: json['MonthGroup'] as String?,
      DaybookCode: json['DaybookCode'] as String?,
      DocNumber: json['DocNumber'] as String?,
      DNumber: json['DNumber'] as String?,
      DaybookType: (json['DaybookType'] as num?)?.toInt(),
      HasteCode: json['HasteCode'] as String?,
      HasteName: json['HasteName'] as String?,
      AccountCode: json['AccountCode'] as String?,
      AccountName: json['AccountName'] as String?,
      AccountGroupCode: json['AccountGroupCode'] as String?,
      AccountGroupName: json['AccountGroupName'] as String?,
      City: json['City'] as String?,
      BrokerCode: json['BrokerCode'] as String?,
      BrokerName: json['BrokerName'] as String?,
      ItemCode: json['ItemCode'] as String?,
      ItemName: json['ItemName'] as String?,
      PartNumber: json['PartNumber'] as String?,
      OrdQuantity1: (json['OrdQuantity1'] as num?)?.toDouble(),
      OrdQuantity2: (json['OrdQuantity2'] as num?)?.toDouble(),
      OrdQuantity3: (json['OrdQuantity3'] as num?)?.toDouble(),
      GrossQuantity1: (json['GrossQuantity1'] as num?)?.toDouble(),
      GrossQuantity2: (json['GrossQuantity2'] as num?)?.toDouble(),
      GrossQuantity3: (json['GrossQuantity3'] as num?)?.toDouble(),
      Quantity: (json['Quantity'] as num?)?.toDouble(),
      ItemRate: (json['ItemRate'] as num?)?.toDouble(),
      IsClosed: json['IsClosed'] as String?,
      OrdAmount: (json['OrdAmount'] as num?)?.toDouble(),
      OLineID: (json['OLineID'] as num?)?.toInt(),
      LineNumber: (json['LineNumber'] as num?)?.toInt(),
      InvDate: json['InvDate'] as String?,
      InvDocNumber: json['InvDocNumber'] as String?,
      BillDate: json['BillDate'] as String?,
      BillNumber: json['BillNumber'] as String?,
      SaleBillDate: json['SaleBillDate'] as String?,
      SaleBillNumber: json['SaleBillNumber'] as String?,
      InvAccountCode: json['InvAccountCode'] as String?,
      InvAccountName: json['InvAccountName'] as String?,
      InvQuantity1: (json['InvQuantity1'] as num?)?.toDouble(),
      InvQuantity2: (json['InvQuantity2'] as num?)?.toDouble(),
      InvQuantity3: (json['InvQuantity3'] as num?)?.toDouble(),
      InvQuantity: (json['InvQuantity'] as num?)?.toDouble(),
      InvAmount: (json['InvAmount'] as num?)?.toDouble(),
      BalanceQuantity1: (json['BalanceQuantity1'] as num?)?.toDouble(),
      BalanceQuantity2: (json['BalanceQuantity2'] as num?)?.toDouble(),
      BalanceQuantity3: (json['BalanceQuantity3'] as num?)?.toDouble(),
      BalanceQuantity2Amount:
          (json['BalanceQuantity2Amount'] as num?)?.toDouble(),
      BalanceQuantity: (json['BalanceQuantity'] as num?)?.toDouble(),
      Days: (json['Days'] as num?)?.toInt(),
      CoCode: json['CoCode'] as String?,
      InvLRNo: json['InvLRNo'] as String?,
      OrderHNotes: json['OrderHNotes'] as String?,
      OrderLiNotes: json['OrderLiNotes'] as String?,
      OrderLiRemarks: json['OrderLiRemarks'] as String?,
      OrderItemDescription: json['OrderItemDescription'] as String?,
      NoOfDesign: (json['NoOfDesign'] as num?)?.toInt(),
      QtyPerDesign: (json['QtyPerDesign'] as num?)?.toInt(),
      ItemGroupCode: json['ItemGroupCode'] as String?,
      ScreenCode: json['ScreenCode'] as String?,
      ScreenName: json['ScreenName'] as String?,
      ItemPackingCode: json['ItemPackingCode'] as String?,
      ItemPackingName: json['ItemPackingName'] as String?,
      IsClosedWithQty: json['IsClosedWithQty'] as String?,
      Status: json['Status'] as String?,
    );

Map<String, dynamic> _$$OrderModelImplToJson(_$OrderModelImpl instance) =>
    <String, dynamic>{
      'ReferenceNo': instance.ReferenceNo,
      'TrTransportName': instance.TrTransportName,
      'TrLRNo': instance.TrLRNo,
      'TrLRDate': instance.TrLRDate,
      'TrNoOfParcel': instance.TrNoOfParcel,
      'TrSourceCity': instance.TrSourceCity,
      'TrStation': instance.TrStation,
      'DeliveryCode': instance.DeliveryCode,
      'DeliveryName': instance.DeliveryName,
      'AccountAddress': instance.AccountAddress,
      'SPEQOHID': instance.SPEQOHID,
      'SPEQOLiID': instance.SPEQOLiID,
      'dbktype': instance.dbktype,
      'OrderDate': instance.OrderDate,
      'SPEQOhSPEQOLi': instance.SPEQOhSPEQOLi,
      'MonthName': instance.MonthName,
      'MonthGroup': instance.MonthGroup,
      'DaybookCode': instance.DaybookCode,
      'DocNumber': instance.DocNumber,
      'DNumber': instance.DNumber,
      'DaybookType': instance.DaybookType,
      'HasteCode': instance.HasteCode,
      'HasteName': instance.HasteName,
      'AccountCode': instance.AccountCode,
      'AccountName': instance.AccountName,
      'AccountGroupCode': instance.AccountGroupCode,
      'AccountGroupName': instance.AccountGroupName,
      'City': instance.City,
      'BrokerCode': instance.BrokerCode,
      'BrokerName': instance.BrokerName,
      'ItemCode': instance.ItemCode,
      'ItemName': instance.ItemName,
      'PartNumber': instance.PartNumber,
      'OrdQuantity1': instance.OrdQuantity1,
      'OrdQuantity2': instance.OrdQuantity2,
      'OrdQuantity3': instance.OrdQuantity3,
      'GrossQuantity1': instance.GrossQuantity1,
      'GrossQuantity2': instance.GrossQuantity2,
      'GrossQuantity3': instance.GrossQuantity3,
      'Quantity': instance.Quantity,
      'ItemRate': instance.ItemRate,
      'IsClosed': instance.IsClosed,
      'OrdAmount': instance.OrdAmount,
      'OLineID': instance.OLineID,
      'LineNumber': instance.LineNumber,
      'InvDate': instance.InvDate,
      'InvDocNumber': instance.InvDocNumber,
      'BillDate': instance.BillDate,
      'BillNumber': instance.BillNumber,
      'SaleBillDate': instance.SaleBillDate,
      'SaleBillNumber': instance.SaleBillNumber,
      'InvAccountCode': instance.InvAccountCode,
      'InvAccountName': instance.InvAccountName,
      'InvQuantity1': instance.InvQuantity1,
      'InvQuantity2': instance.InvQuantity2,
      'InvQuantity3': instance.InvQuantity3,
      'InvQuantity': instance.InvQuantity,
      'InvAmount': instance.InvAmount,
      'BalanceQuantity1': instance.BalanceQuantity1,
      'BalanceQuantity2': instance.BalanceQuantity2,
      'BalanceQuantity3': instance.BalanceQuantity3,
      'BalanceQuantity2Amount': instance.BalanceQuantity2Amount,
      'BalanceQuantity': instance.BalanceQuantity,
      'Days': instance.Days,
      'CoCode': instance.CoCode,
      'InvLRNo': instance.InvLRNo,
      'OrderHNotes': instance.OrderHNotes,
      'OrderLiNotes': instance.OrderLiNotes,
      'OrderLiRemarks': instance.OrderLiRemarks,
      'OrderItemDescription': instance.OrderItemDescription,
      'NoOfDesign': instance.NoOfDesign,
      'QtyPerDesign': instance.QtyPerDesign,
      'ItemGroupCode': instance.ItemGroupCode,
      'ScreenCode': instance.ScreenCode,
      'ScreenName': instance.ScreenName,
      'ItemPackingCode': instance.ItemPackingCode,
      'ItemPackingName': instance.ItemPackingName,
      'IsClosedWithQty': instance.IsClosedWithQty,
      'Status': instance.Status,
    };
