import 'package:rupay/shared/typedef.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'OrderModel.freezed.dart';
part 'OrderModel.g.dart';


@freezed
class OrderModel with _$OrderModel {
  factory OrderModel({
  String? ReferenceNo,
  String? TrTransportName,
  String? TrLRNo,
  String? TrLRDate,
  String? TrNoOfParcel,
  String? TrSourceCity,
  String? TrStation,
  String? DeliveryCode,
  String? DeliveryName,
  String? AccountAddress,
  int? SPEQOHID,
  int? SPEQOLiID,
  String? dbktype,
  String? OrderDate,
  int? SPEQOhSPEQOLi,
  String? MonthName,
  String? MonthGroup,
  String? DaybookCode,
  String? DocNumber,
  String? DNumber,
  int? DaybookType,
  String? HasteCode,
  String? HasteName,
  String? AccountCode,
  String? AccountName,
  String? AccountGroupCode,
  String? AccountGroupName,
  String? City,
  String? BrokerCode,
  String? BrokerName,
  String? ItemCode,
  String? ItemName,
  String? PartNumber,
  double? OrdQuantity1,
  double? OrdQuantity2,
  double? OrdQuantity3,
  double? GrossQuantity1,
  double? GrossQuantity2,
  double? GrossQuantity3,
  double? Quantity,
  double? ItemRate,
  String? IsClosed,
  double? OrdAmount,
  int? OLineID,
  int? LineNumber,
  String? InvDate,
  String? InvDocNumber,
  String? BillDate,
  String? BillNumber,
  String? SaleBillDate,
  String? SaleBillNumber,
  String? InvAccountCode,
  String? InvAccountName,
  double? InvQuantity1,
  double? InvQuantity2,
  double? InvQuantity3,
  double? InvQuantity,
  double? InvAmount,
  double? BalanceQuantity1,
  double? BalanceQuantity2,
  double? BalanceQuantity3,
  double? BalanceQuantity2Amount,
  double? BalanceQuantity,
  int? Days,
  String? CoCode,
  String? InvLRNo,
  String? OrderHNotes,
  String? OrderLiNotes,
  String? OrderLiRemarks,
  String? OrderItemDescription,
  int? NoOfDesign,
  int? QtyPerDesign,
  String? ItemGroupCode,
  String? ScreenCode,
  String? ScreenName,
  String? ItemPackingCode,
  String? ItemPackingName,
  String? IsClosedWithQty,
  String? Status

}) = _OrderModel;

  factory OrderModel.fromJson(JSON json) => _$OrderModelFromJson(json);
}
