// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'OutstandingModel.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$OutstandingModelImpl _$$OutstandingModelImplFromJson(
        Map<String, dynamic> json) =>
    _$OutstandingModelImpl(
      ID: (json['ID'] as num?)?.toInt(),
      UID: json['UID'] as String?,
      COCODE: json['COCODE'] as String?,
      TYP: json['TYP'] as String?,
      OSTypeName: json['OSTypeName'] as String?,
      AccountAddress: json['AccountAddress'] as String?,
      TrSourceCity: json['TrSourceCity'] as String?,
      OSType: (json['OSType'] as num?)?.toInt(),
      DaybookCodeID: json['DaybookCodeID'] as String?,
      TxnDate: json['TxnDate'] as String?,
      DaybookCode: json['DaybookCode'] as String?,
      DocNumber: json['DocNumber'] as String?,
      DocumentNumber: json['DocumentNumber'] as String?,
      DocumentDate: json['DocumentDate'] as String?,
      DocNo: json['DocNo'] as String?,
      AccountCode: json['AccountCode'] as String?,
      AccountName: json['AccountName'] as String?,
      BillRemarks: json['BillRemarks'] as String?,
      BrokerNAme: json['BrokerNAme'] as String?,
      DueDate: json['DueDate'] as String?,
      DueDays: (json['DueDays'] as num?)?.toInt(),
      TxnDays: (json['TxnDays'] as num?)?.toInt(),
      DeliveryName: json['DeliveryName'] as String?,
      BasicAmount: (json['BasicAmount'] as num?)?.toDouble(),
      NetAmount: (json['NetAmount'] as num?)?.toDouble(),
      OtherAmount1: (json['OtherAmount1'] as num?)?.toDouble(),
      ChequeDate: json['ChequeDate'] as String?,
      AdjTxnDate: json['AdjTxnDate'] as String?,
      AdjDaybookCode: json['AdjDaybookCode'] as String?,
      BankCode: json['BankCode'] as String?,
      ChequeNo: json['ChequeNo'] as String?,
      ReturnAdjAmount: (json['ReturnAdjAmount'] as num?)?.toDouble(),
      OtherAdjAmount: (json['OtherAdjAmount'] as num?)?.toDouble(),
      AdjustedAmount: (json['AdjustedAmount'] as num?)?.toDouble(),
      ReturnTotalAdjAmount: (json['ReturnTotalAdjAmount'] as num?)?.toDouble(),
      OtherTotalAdjAmount: (json['OtherTotalAdjAmount'] as num?)?.toDouble(),
      TotalAdjAmount: (json['TotalAdjAmount'] as num?)?.toDouble(),
      BalanceAmount: (json['BalanceAmount'] as num?)?.toDouble(),
      NetOSAmount: (json['NetOSAmount'] as num?)?.toDouble(),
      ADD1: json['ADD1'] as String?,
      ADD2: json['ADD2'] as String?,
      PINCODE: json['PINCODE'] as String?,
      CITY: json['CITY'] as String?,
      GSTIN: json['GSTIN'] as String?,
      MOBILE: json['MOBILE'] as String?,
    );

Map<String, dynamic> _$$OutstandingModelImplToJson(
        _$OutstandingModelImpl instance) =>
    <String, dynamic>{
      'ID': instance.ID,
      'UID': instance.UID,
      'COCODE': instance.COCODE,
      'TYP': instance.TYP,
      'OSTypeName': instance.OSTypeName,
      'AccountAddress': instance.AccountAddress,
      'TrSourceCity': instance.TrSourceCity,
      'OSType': instance.OSType,
      'DaybookCodeID': instance.DaybookCodeID,
      'TxnDate': instance.TxnDate,
      'DaybookCode': instance.DaybookCode,
      'DocNumber': instance.DocNumber,
      'DocumentNumber': instance.DocumentNumber,
      'DocumentDate': instance.DocumentDate,
      'DocNo': instance.DocNo,
      'AccountCode': instance.AccountCode,
      'AccountName': instance.AccountName,
      'BillRemarks': instance.BillRemarks,
      'BrokerNAme': instance.BrokerNAme,
      'DueDate': instance.DueDate,
      'DueDays': instance.DueDays,
      'TxnDays': instance.TxnDays,
      'DeliveryName': instance.DeliveryName,
      'BasicAmount': instance.BasicAmount,
      'NetAmount': instance.NetAmount,
      'OtherAmount1': instance.OtherAmount1,
      'ChequeDate': instance.ChequeDate,
      'AdjTxnDate': instance.AdjTxnDate,
      'AdjDaybookCode': instance.AdjDaybookCode,
      'BankCode': instance.BankCode,
      'ChequeNo': instance.ChequeNo,
      'ReturnAdjAmount': instance.ReturnAdjAmount,
      'OtherAdjAmount': instance.OtherAdjAmount,
      'AdjustedAmount': instance.AdjustedAmount,
      'ReturnTotalAdjAmount': instance.ReturnTotalAdjAmount,
      'OtherTotalAdjAmount': instance.OtherTotalAdjAmount,
      'TotalAdjAmount': instance.TotalAdjAmount,
      'BalanceAmount': instance.BalanceAmount,
      'NetOSAmount': instance.NetOSAmount,
      'ADD1': instance.ADD1,
      'ADD2': instance.ADD2,
      'PINCODE': instance.PINCODE,
      'CITY': instance.CITY,
      'GSTIN': instance.GSTIN,
      'MOBILE': instance.MOBILE,
    };
